"""switch to sqlite

Revision ID: 5e69b646c757
Revises: 
Create Date: 2025-11-19 23:51:54.865634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e69b646c757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_table('task_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('due_datetime_offset_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_definitions_id'), 'task_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_task_definitions_workflow_definition_id'), 'task_definitions', ['workflow_definition_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'archived', 'pending', name='workflowstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('due_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_id'), 'workflow_instances', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_share_token'), 'workflow_instances', ['share_token'], unique=True)
    op.create_index(op.f('ix_workflow_instances_user_id'), 'workflow_instances', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_instances_workflow_definition_id'), 'workflow_instances', ['workflow_definition_id'], unique=False)
    op.create_table('task_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'in_progress', name='taskstatus'), nullable=False),
    sa.Column('due_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_instances_id'), 'task_instances', ['id'], unique=False)
    op.create_index(op.f('ix_task_instances_workflow_instance_id'), 'task_instances', ['workflow_instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_instances_workflow_instance_id'), table_name='task_instances')
    op.drop_index(op.f('ix_task_instances_id'), table_name='task_instances')
    op.drop_table('task_instances')
    op.drop_index(op.f('ix_workflow_instances_workflow_definition_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_user_id'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_share_token'), table_name='workflow_instances')
    op.drop_index(op.f('ix_workflow_instances_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_task_definitions_workflow_definition_id'), table_name='task_definitions')
    op.drop_index(op.f('ix_task_definitions_id'), table_name='task_definitions')
    op.drop_table('task_definitions')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
